name: Dokploy Build

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

permissions:
  contents: read
  statuses: write

jobs:
  dokploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Dokploy build
        run: |
          # Example command — adapt to your setup
          npx dokploy build --env production

      - name: Report status (optional)
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          STATE=success
          if [ "${{ job.status }}" != "success" ]; then
            STATE=failure
          fi

          curl -s -X POST \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${REPO}/statuses/${SHA}" \
            -d "{
              \"state\": \"${STATE}\",
              \"target_url\": \"${{ github.server_url }}/${REPO}/actions/runs/${{ github.run_id }}\",
              \"description\": \"Dokploy build ${STATE}\",
              \"context\": \"dokploy/build\"
            }"
